export const FILL_UP_FORM_SUCCESS = "FILL_UP_FORM_SUCCESS";
export const FILL_UP_FORM_FAILED = "FILL_UP_FORM_FAILED";
export const FILL_UP_FORM_LOADING = "FILL_UP_FORM_LOADING";
export const FILL_UP_FORM_RESET = "FILL_UP_FORM_RESET";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAILED = "GET_FORM_FAILED";
export const GET_FORM_LOADING = "GET_FORM_LOADING";
export const GET_FORM_RESET = "GET_FORM_RESET";